### ISSUE TITLE
Could not find gradle.plugin.com.github.kolleroot.gradle.kubernetes:gradle-kubernetes-plugin:0.1.0.

### ISSUE THREAD

**Issue by lpegoraro** [kolleroot/gradle-kubernetes-plugin#1]
Could not find gradle.plugin.com.github.kolleroot.gradle.kubernetes:gradle-kubernetes-plugin:0.1.0.
Searched in the following locations:
    https://repo.maven.apache.org/maven2/gradle/plugin/com/github/kolleroot/gradle/kubernetes/gradle-kubernetes-plugin/0.1.0/gradle-kubernetes-plugin-0.1.0.pom
    https://repo.maven.apache.org/maven2/gradle/plugin/com/github/kolleroot/gradle/kubernetes/gradle-kubernetes-plugin/0.1.0/gradle-kubernetes-plugin-0.1.0.jar
    https://jcenter.bintray.com/gradle/plugin/com/github/kolleroot/gradle/kubernetes/gradle-kubernetes-plugin/0.1.0/gradle-kubernetes-plugin-0.1.0.pom
    https://jcenter.bintray.com/gradle/plugin/com/github/kolleroot/gradle/kubernetes/gradle-kubernetes-plugin/0.1.0/gradle-kubernetes-plugin-0.1.0.jar
    https://plugins.gradle.org/m2/gradle/plugin/com/github/kolleroot/gradle/kubernetes/gradle-kubernetes-plugin/0.1.0/gradle-kubernetes-plugin-0.1.0.pom
    https://plugins.gradle.org/m2/gradle/plugin/com/github/kolleroot/gradle/kubernetes/gradle-kubernetes-plugin/0.1.0/gradle-kubernetes-plugin-0.1.0.jar

All of them returned 404 for me.

**Comment by kolleroot** [comment]
Thanks for reporting the issue. The plugin isn't published in the gradle repository as the hostPort feature in kubernetes was dropped shortly after I finished implementing this project. The hostPort feature is required to run a registry in the cluster without a tls certificate as docker only allows unsecured communication via localhost e.g. localhost:5000.

To get this working again one would need to setup a registry with a valid tls certificate (the registry doesn't neet to be public and can be selfsigned as long as all nodes and the developer pc trust the certificate). Then the setup and cleanup logic for the docker registry connection has to be reimplemented.

To summ it up, I wouldn't recommend using this plugin in it's current state. I would rather recommend using a initContainer to setup everything built by gradle and a standard java (or wildfly or ...) docker image to start the application.
